### ISSUE TITLE
Kestrel实现前后端websockt通讯

### ISSUE THREAD

**Issue by wujiejie2011** [xljiulang/KestrelApp#2]
目前项目使用dotnetty实现前后端的数据交互，如果换成Kestrel，应该如何实现呢，我看到源码里面没有ws://开头的websocket服务

**Comment by xljiulang** [comment]
websocekt是kestrel内置支持的协议，如果你的直接使用websocket做应用层协议的话，可以直接参考：https://learn.microsoft.com/zh-cn/aspnet/core/fundamentals/websockets?view=aspnetcore-6.0

如果你是使用websocket做传输层，可以参考本项目的
```c#
// Telnet over WebSocket
app.MapConnectionHandler<TelnetConnectionHandler>("/telnet");
```
运行KestrelApp项目之后，在浏览器F12 ->控制台 粘贴如下js，即可测试
```js
var ws = new WebSocket("ws://localhost:5005/telnet"); 
ws.onopen = function(){ 
    console.log("open");
　　ws.send("telnet over websocket!\r\n");  
}
ws.onmessage = function(e){　　 
　　console.log(e.data);
}
```

**Comment by wujiejie2011** [comment]
非常感谢九哥的指点，webscoket通讯已实现，如果是在缺少分隔符的前提下，有什么方法能够有效的解决数据不粘包的问题呀

**Comment by xljiulang** [comment]
websocket是基于帧传输的，你完全可以一帧一条业务数据。ws的一次send就是一帧。

**Comment by xljiulang** [comment]
如果有强烈的 自定义应用协议 的需求，而传输层不拘泥于仅仅是websocket，那你可以设计一个最简单的echo协议：https://github.com/xljiulang/KestrelApp/blob/master/KestrelApp.Echo/EchoConnectionHandler.cs#L35

**Comment by wujiejie2011** [comment]
感谢九哥，学习到了，哈哈

**Comment by sgf** [comment]
Kestrel 应该只是tcp吧.tcp协议除了上bbr,否则感觉没啥可玩性.
